Attempt to fix bug with generation/installation of gem from GitHub.  Too long version string.
It appears RubyGems does not like version strings beyond major.minor.build

Our four segment string might have been causing the following error when trying to install:

~/src/git\ > sudo gem install grempe-xmpp4r
ERROR:  While executing gem ... (ArgumentError)
    comparison of String with 2 failed

See RubyGem docs:

http://www.rubygems.org/read/chapter/7